# Generated by Django 4.0.4 on 2022-05-27 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='project 1', max_length=200)),
                ('domain', models.CharField(default='Machine Learning', max_length=200)),
                ('small_desc', models.CharField(default='small description', max_length=500)),
                ('large_desc', models.CharField(default='large description', max_length=1500)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('source_link', models.CharField(default='https://www.google.com', max_length=200)),
                ('deployment_link', models.CharField(default='https://www.google.com', max_length=200)),
                ('tags', models.CharField(default='MySQL,Python,ML,', max_length=700)),
                ('screenshot1', models.ImageField(upload_to='uploads/screenshots')),
                ('screenshot2', models.ImageField(upload_to='uploads/screenshots')),
                ('screenshot3', models.ImageField(upload_to='uploads/screenshots')),
                ('screenshot4', models.ImageField(upload_to='uploads/screenshots')),
            ],
        ),
    ]
