# Generated by Django 4.0.4 on 2022-06-05 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cvhome', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_id', models.CharField(default='pradip', max_length=50)),
                ('name', models.CharField(default='Pradip Bankar', max_length=100)),
                ('photo', models.ImageField(upload_to='')),
            ],
        ),
    ]
