# Generated by Django 4.0.4 on 2022-06-12 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cvhome', '0002_mydetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='mydetails',
            name='no_of_academic_projects',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='mydetails',
            name='no_of_internships',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='mydetails',
            name='no_of_paid_projects',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='mydetails',
            name='no_of_projects',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='mydetails',
            name='photo',
            field=models.ImageField(upload_to='static/images/profile_pic'),
        ),
    ]
