# Generated by Django 4.0.4 on 2022-06-12 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cvhome', '0005_mydetails_about_me'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mydetails',
            name='about_me',
            field=models.TextField(default="<b>Lorem</b> ipsum dolor sit amet, consectetur adipiscing elit. Duis interdum ante a porta blandit.<input type='text' placeholder='testing'/> Quisque velit tortor, ultricies in quam ut, luctus convallis metus. Nunc vitae felis rutrum, mattis justo quis, bibendum tellus. Integer bibendum eget dolor nec venenatis. Aliquam erat volutpat. Etiam et est vitae turpis accumsan vulputate. Curabitur et vehicula nisl, eu congue dolor. Vivamus nec hendrerit mi Nulla consequat tempor."),
        ),
        migrations.AlterField(
            model_name='project',
            name='large_desc',
            field=models.TextField(default='large description'),
        ),
        migrations.AlterField(
            model_name='project',
            name='small_desc',
            field=models.TextField(default='small description'),
        ),
    ]
