# Generated by Django 4.0.4 on 2022-07-16 19:52

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cvhome', '0006_alter_mydetails_about_me_alter_project_large_desc_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(default='developer', max_length=200)),
                ('start_date', models.DateField(default=datetime.date(2022, 7, 16))),
                ('end_date', models.DateField(default=datetime.date(2022, 7, 16))),
                ('about', models.TextField(default='learned so many things')),
                ('tags', models.CharField(default='React,MongoDB', max_length=1000)),
                ('company', models.CharField(default='microsoft', max_length=200)),
                ('location', models.CharField(default='Aurangabad, Maharashtra', max_length=300)),
                ('presently_working', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Internship',
            fields=[
                ('experience_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='cvhome.experience')),
                ('stipend', models.IntegerField(default=15000)),
            ],
            bases=('cvhome.experience',),
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('experience_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='cvhome.experience')),
                ('salary', models.IntegerField(default=30000)),
            ],
            bases=('cvhome.experience',),
        ),
    ]
