# Generated by Django 4.0.4 on 2022-07-16 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cvhome', '0007_experience_internship_job'),
    ]

    operations = [
        migrations.AddField(
            model_name='experience',
            name='visible_on_cv',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='experience',
            name='visible_on_resume',
            field=models.BooleanField(default=True),
        ),
    ]
