# Generated by Django 4.0.4 on 2022-07-17 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cvhome', '0009_alter_experience_end_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='visible_on_cv',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='project',
            name='visible_on_resume',
            field=models.BooleanField(default=True),
        ),
    ]
