# Generated by Django 4.0.4 on 2022-07-17 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cvhome', '0010_project_visible_on_cv_project_visible_on_resume'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='project_banner',
            field=models.ImageField(default=None, upload_to='uploads/project/banners'),
        ),
    ]
