# Generated by Django 4.0.4 on 2022-07-17 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cvhome', '0011_project_project_banner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='screenshot1',
            field=models.ImageField(null=True, upload_to='uploads/screenshots'),
        ),
        migrations.AlterField(
            model_name='project',
            name='screenshot2',
            field=models.ImageField(null=True, upload_to='uploads/screenshots'),
        ),
        migrations.AlterField(
            model_name='project',
            name='screenshot3',
            field=models.ImageField(null=True, upload_to='uploads/screenshots'),
        ),
        migrations.AlterField(
            model_name='project',
            name='screenshot4',
            field=models.ImageField(null=True, upload_to='uploads/screenshots'),
        ),
    ]
