# Generated by Django 4.0.4 on 2022-07-21 18:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cvhome', '0012_alter_project_screenshot1_alter_project_screenshot2_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institute', models.CharField(default='Government College of Engineering, Aurangabad', max_length=200)),
                ('edu_level', models.CharField(default='B.Tech.', max_length=50)),
                ('start_date', models.DateField(default=django.utils.timezone.now)),
                ('end_date', models.DateField(default=django.utils.timezone.now)),
                ('specialization', models.CharField(default='Information Technology', max_length=200)),
            ],
        ),
    ]
