# Generated by Django 4.0.4 on 2022-07-21 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cvhome', '0013_education'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='visible_on_cv',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='education',
            name='visible_on_resume',
            field=models.BooleanField(default=True),
        ),
    ]
